version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4

executors:
  docker-node:
    docker:
      - image: circleci/node:12

jobs:
  resolve_latest:
    executor: docker-node
    steps:
      - checkout
      - run:
          name: Resolve latest keep-ecdsa
          working_directory: ~/project/solidity
          command: npm update @keep-network/keep-ecdsa
      - persist_to_workspace:
          root: .
          paths:
            - solidity/package.json
            - solidity/package-lock.json
  # GitHub Actions equivalent of this job (.github/workflows/contracts.yml)
  # has been created as part of work on RFC-18
  compile_contracts:
    executor: docker-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          working_directory: ~/project/solidity
          command: npm ci
      - run:
          name: Compile contracts
          working_directory: ~/project/solidity
          command: npx truffle compile
      # Persist for downstream use.
      - persist_to_workspace:
          root: .
          paths:
           - solidity/node_modules
           - solidity/build/contracts
  build_relay_maintainer_initcontainer:
    executor: docker-node
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Docker build
          command: |
            mkdir -p /tmp/relay-maintainer/docker-images
            cd infrastructure/kube/templates/relay-maintainer/initcontainer
            npm upgrade @keep-network/tbtc
            docker build \
              -t $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/initcontainer-provision-relay-maintainer .
      - run:
          name: Save initcontainer-provision-relay-maintainer image
          command: |
            docker save -o /tmp/relay-maintainer/docker-images/initcontainer-provision-relay-maintainer.tar $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/initcontainer-provision-relay-maintainer
      - persist_to_workspace:
          root: /tmp/relay-maintainer
          paths:
            - docker-images
  publish_relay_maintainer_initcontainer:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/relay-maintainer
      - run:
          name: Load Docker images
          command: |
            docker load -i /tmp/relay-maintainer/docker-images/initcontainer-provision-relay-maintainer.tar
      - gcp-gcr/gcr-auth:
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE_A
          # This param doesn't actually set anything, leaving here as a reminder to check when they fix it.
          gcloud-service-key: GCLOUD_SERVICE_KEY
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: $GCR_REGISTRY_URL
          image: initcontainer-provision-relay-maintainer
          tag: latest

workflows:
  version: 2
  build_publish_keep_dev:
    jobs:
      - compile_contracts
      - build_relay_maintainer_initcontainer:
          filters:
            branches:
              only: main
          context: keep-dev
      - publish_relay_maintainer_initcontainer:
          filters:
            branches:
              only: main
          context: keep-dev
          requires:
            - build_relay_maintainer_initcontainer
  migrate_build_publish_keep_test:
    jobs:
      - keep_test_approval:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/.*/
      - resolve_latest:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/.*/
          requires:
            - keep_test_approval
      - compile_contracts:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/.*/
          requires:
            - resolve_latest
      - build_relay_maintainer_initcontainer:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/.*/
          context: keep-test
      - publish_relay_maintainer_initcontainer:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/.*/
          context: keep-test
          requires:
            - build_relay_maintainer_initcontainer
