---
apiVersion: v1
kind: Service
metadata:
  name: bcoin
  namespace: default
  labels:
    app: bitcoin-node
    type: bcoin
spec:
  ports:
  - port: 18332
    targetPort: 18332
    name: testnet-rpc
  - port: 18333
    targetPort: 18333
    name: testnet
  selector:
    app: bitcoin-node
    type: bcoin
