---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: relay-maintainer
  namespace: default
  labels:
    keel.sh/policy: all
    app: maintainer
    type: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintainer
      type: relay
  template:
    metadata:
      labels:
        app: maintainer
        type: relay
    spec:

      initContainers:
        - name: initcontainer-provision-relay-maintainer
          image: gcr.io/keep-test-f3e0/initcontainer-provision-relay-maintainer:set-infura-project-id
          imagePullPolicy: Always
          env:

            - name: ETH_RPC_URL
              valueFrom:
                configMapKeyRef:
                  name: eth-network-ropsten
                  key: rpc-url

            - name: ETH_NETWORK_ID
              valueFrom:
                configMapKeyRef:
                  name: eth-network-ropsten
                  key: network-id

            - name: ETH_NETWORK_NAME
              value: ropsten

            - name: INFURA_PROJECT_ID
              value: 59fb36a36fa4474b890c13dd30038be5

            - name: RELAY_MAINTAINER_ETH_ACCOUNT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eth-account-info
                  key: account-25-address

            - name: RELAY_MAINTAINER_ETH_ACCOUNT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: eth-account-privatekeys
                  key: account-25

            - name: CONTRACT_OWNER_ETH_ACCOUNT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eth-network-ropsten
                  key: contract-owner-eth-account-address

            - name: CONTRACT_OWNER_ETH_ACCOUNT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: eth-network-ropsten
                  key: contract-owner-eth-account-private-key

            - name: BCOIN_HOST
              value: bcoin.default.svc.cluster.local

            - name: BCOIN_PORT
              value: '18332'

            - name: BCOIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bcoin
                  key: http-api-key

            - name: RELAY_CONTRACT_ADDRESS
              value: '0xfb8476462BFf9B4455CDB382dB0187c77D89618E'

          volumeMounts:
            - name: relay-maintainer-env
              mountPath: /mnt/relay-maintainer
          command: ['node', '/tmp/provision-relay-maintainer.js']

      containers:
        - name: relay-maintainer
          image: gcr.io/keep-test-f3e0/relay-maintainer
          imagePullPolicy: Always
          volumeMounts:
            - name: relay-maintainer-env
              mountPath: /mnt/relay-maintainer

      volumes:
        - name: relay-maintainer-env
          persistentVolumeClaim:
            claimName: relay-maintainer-env

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-maintainer-env
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
