---
apiVersion: batch/v1
kind: Job
metadata:
  name: tbtc-electrumx-compact-history
  namespace: tbtc
  labels:
    app: tbtc
    type: electrumx-compact-history
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: tbtc
        type: electrumx-server
    spec:
      restartPolicy: Never
      containers:
      - name: electrumx-server
        image: lukechilds/electrumx
        command: ["/electrumx/electrumx_compact_history"]
        # Full list of env vars: https://electrumx.readthedocs.io/en/latest/environment.html
        env:
          - name: DB_DIRECTORY
            value: /mnt/electrum/data
          - name: SSL_CERTFILE
            value: /mnt/electrum/cert/tls.crt
          - name: SSL_KEYFILE
            value: /mnt/electrum/cert/tls.key
          - name: DAEMON_URL
            valueFrom:
              secretKeyRef:
                name: bcoin
                key: bcoin-url
          - name: COIN
            value: BitcoinSegwit
          - name: NET
            value: testnet
          - name: COST_SOFT_LIMIT
            value: '0'
          - name: COST_HARD_LIMIT
            value: '0'
          - name: LOG_LEVEL
            value: debug
        volumeMounts:
          - name: tbtc-electrumx-server-data
            mountPath: /mnt/electrum/data
      volumes:
      - name: tbtc-electrumx-server-data
        persistentVolumeClaim:
          claimName: tbtc-electrumx-server-data-tbtc-electrumx-server-0
