# This is a TOML configuration file.

# Connection details of Ethereum blockchain.
[ethereum]
  URL = ""
  URLRPC = ""

# Account details for Ethereum blockchain.
[ethereum.account]
  KeyFile = ""

# Addresses of contracts deployed on Ethereum blockchain.
[ethereum.ContractAddresses]
  Relay = ""

# Connection details of Bitcoin blockchain
[bitcoin]
  URL = ""
  Password = ""
  Username = ""

# The port on which the `/metrics` endpoint will be available and the frequency
# with which the metrics will be collected can be customized using the
# below parameters. `ChainMetricsTick` determines the tick of metrics related
# with BTC and host chains and should be set carefully as it may greatly
# increase the number of requests sent to the chain clients. `NodeMetricsTick`
# sets the tick for metrics related with the relay node itself.
[Metrics]
  Port = ""
  ChainMetricsTick = ""
  NodeMetricsTick = ""

[Relay]
# Maximum number of headers which can be relayed in one batch. This setting
# also implies the frequency of difficulty updates. A bigger value means
# that biggest batches are used and updates occur less often but the summarized
# transaction cost incurred by the relay is lower. On the other hand, lower
# batch size means batch size are smaller and updates occur more frequently
# at a price of higher cost.
#
HeadersBatchSize = ""
